### ISSUE TITLE
composed view unable to access $parent scope

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#145]
repro: http://plnkr.co/edit/i7DJo6

Issue is [here](https://github.com/aurelia/templating-resources/blob/master/src/compose.js#L63).  Need to flow the "scope" (bindingContext + overrideContext) through the compose.

cc @jods4 @zebrooks

**Comment by jods4** [comment]
This was a breaking change for us. It was even document as working but it does not anymore after the pre-beta release.

**Comment by EisenbergEffect** [comment]
We are working on the fix. Apologies.

**Comment by jods4** [comment]
No problem Rob, I guess this is life with betas. We had lots of things breaking with this release, though:
- I have yet to debug why navigation links don't work anymore. We use `pushState` API and I can see the URL changed to a `#` hash route and nothing happens :( Will report more details when I figure this out.
- I also have another breaking thing with a `$parent.$parent` binding in a custom element we made, I started debugging this but for now I don't quite understand what is happening.
- I've had issues with `@children` not behaving exactly like `@sync` but I could work around it rather easily by modifying our code.

**Comment by EisenbergEffect** [comment]
FYI `@children` only selected immediate child content of the custom element now.

**Comment by jods4** [comment]
@EisenbergEffect yes, thanks I noticed that. Out of curiosity what is the reasoning behind that? My use case is direct children anyway, but in a way isn't that less powerful than it was before? Is it to rule out the confusion ensued by nesting custom elements using the same `@sync` selectors?

**Comment by EisenbergEffect** [comment]
There were several reasons. It does eliminate the confusion and bugs caused by selecting across component boundaries. There are other ways to fix that, but they are all complicated. It also allows us to more easily share mutation observers for the same element. It also helps to enforce what I think is a better practice in terms or custom element patterns.

That said, it's possible to re-enable the old sync behavior if anyone needs it. The child/children and previous sync decorators are actually built on top of an extensible system. If you are curious, take a look at the decorator code and you'll see how the pieces fit.

**Comment by jods4** [comment]
@EisenbergEffect I am in no need for the old behaviour, it was just out of curiosity!
I will try the fix for this issue later today.
