### ISSUE TITLE
Support "with" binding similar to knockout

### ISSUE THREAD

**Issue by jaimerivera** [aurelia/templating-resources#16]
In Durandal 2.0 it was possible to expose a view model as a property of a parent view model by using knockout's 'with' binding and state its view.  To aid in portability of existing Durandal apps and to support the particular use case this type of composing is needed.  In the example below "dateRangeVM" is the view model property.  By using the compose binding, a custom view could be specified.
```
<!--Date Range Selection-->
<div class="form-group" data-bind="with: dateRangeVM">
         <div data-bind="compose:{ view: 'dateRangeSelection'}"></div>
</div>
```

There may be a better way to accomplish this in Aurelia with custom elements and behaviors.  The outer view model would need to still have access to the inner view model to query state and values.

**Comment by EisenbergEffect** [comment]
We are working on this now :)

**Comment by PWKad** [comment]
@EisenbergEffect - Not completely working as expected.  I still need to debug more but here is a reference in case anyone else looking at this wants to see if something sticks out.

 https://github.com/PWKad/templating-resources/blob/7056305227bc5a81b2335f49467bb0d590cd636b/src/with.js

**Comment by EisenbergEffect** [comment]
Create the view in the constructor and add it to the view slot immediately. Then, just call bind on it whenever the value changes. See how that works out.

**Comment by EisenbergEffect** [comment]
@PWKad How's it going on this?

**Comment by PWKad** [comment]
Right now the problem is the binding is only triggered by changes to the parent.  I am trying to research the best way to hook in to all of the properties without explicitly managing the observers.  Ex -

`<div with.bind="parentProp"><span>${childProp}</span></div>`

Gets properly bound but not the first time through.  But if we do this - 

`parentProp.childProp = 'red'` it does not trigger the binding to update.  This does -
`parentProp = { childProp = 'blue' }`

I will push out a repo demonstrating this for reference.

**Comment by EisenbergEffect** [comment]
You shouldn't be hooking into all the properties. This sounds like a bug in the binding system. I need a PR for this so I can test this and see if we have an issue and figure out a resolution. Thanks!

**Comment by Zoltu** [comment]
Would the completion of this feature allow me to do something like this:

custom-element.html
```html
<template>
	${this.name}
</template>
```

custom-element.js
```js
export class CustomElement {
	constructor(name) {
		this.name = name;
	}
}
```

app.html
```html
<template>
	<require from="./custom-element"></require>
	<!-- custom-element is just a placeholder until myCustomElement is set -->
	<custom-element with="myCustomElement"></custom-element>
</template>
```

app.js
```js
import { CustomElement } from 'custom-element';
export class App {
	// called at any point in the page lifecycle, as early as view-model construction and as late as in response to user input
	someMethod() {
		this.myCustomElement = new CustomElement("John");
	}
	someOtherMethod() {
		if (this.myCustomElement)
			// expect that this updates the name rendered in the browser
			this.myCustomElement.name = "Jane";
	}
}
```

The expected behavior here is that the `<custom-element>` element in `app.html` would be a placeholder until such time as `this.myCustomElement` was set.

I'm not exactly sure how the lifecycle events would play out (`bind` and `activate` on `CustomElement`), but the critical piece is that `CustomElement` gets its bindings setup so the call to `someOtherMethod` (which results in setting `name` on the custom element) would result in the page being properly updated with the `Jane`.

If this issue doesn't address this concern, I'll create a new issue for it... but this sounds very similar.

**Comment by jods4** [comment]
The current `with` binding does not expose a `$parent` in the binding context, which is a very hard limitation.

A common use case is to bind forms: `<form with.bind="entity"><input value.bind="name" />`. In this use case you frequently need to bind to handlers (click on buttons) or other properties (dropdown values). In KO this was usually achieved with a `$parent.clickHandler` (or `$root`) reference.

I've looked into patching the `with` binding, but this is not trivial. Since the binding context _is_ the entity, exposing a `$parent` property means _modifying the entity itself_. This is bad and can have tons of unexpected consequences (e.g. if the user code iterates over `Object.keys`).

It seems to me that the only clean solution is that Aurelia should be able to bind to "ambient" properties (whatever that may mean: globals, parent context, specific objects). So that bindings such as `with` can expose `$parent` (and maybe others) without modifying the context itself.

I am not sure if this is worthy of a generic ambient scope or just a hard-coded `$parent` chain that is always available.

**Comment by PWKad** [comment]
@jods4 The `with` binding was an experimental feature that is untested and has a broken implementation in some respects.  I would not suggest using it in your app at the moment.

**Comment by jods4** [comment]
I see. 
I hope you'll manage to turn it into an official feature, because it simplifies several use cases a lot.

**Comment by jods4** [comment]
I was thinking about the `$parent` issue, which is a bit tricky.
The best solution -- and it would open up other scenarios -- would be for Aurelia bindings to support "ambient" properties / functions that are tied to the context but not directly on it.

But without that, there's another trick we could pull off. `$parent` could be added as a non-enumerable property. That way we modify the object in a hard to notice way. It could still break though:
- if user code already depends on its own `$parent` property.
- if user code uses `Object.getOwnPropertyNames()`. This is not common, though. Generic code that goes over properties (e.g. serialization) usually uses `for..in` or `Object.keys()`.

I think that would be acceptable, maybe with a warning in the doc. In cases when those condition are unacceptable then `with` shouldn't be used (it's always possible to do without it after all).

**Comment by EisenbergEffect** [comment]
We have the `with` behavior now. We were going to deprecate it but instead we have a way to fix it for the next release :)

**Comment by EisenbergEffect** [comment]
(We are adding a secondary binding context to the binding/templating engine called an overrideContext which can be an alternate source of properties that are available to bind to.)

**Comment by jods4** [comment]
@EisenbergEffect That's my "ambient" scope ;)
How does it work? Is it checked first or after the "normal" context? What's the behaviour with respect to undefined properties at binding time?

It's very nice to have an officially supported `with` binding, that's really handy for forms.
The `overrideContext` will enable interesting new features I think!

Thanks.

**Comment by EisenbergEffect** [comment]
@jdanyow is working on it this evening. We're planning to get it in for the beta. If you have any thoughts on how it should work, please leave those here so he can process those as part of his implementation.

**Comment by jods4** [comment]
@jdanyow @EisenbergEffect I did not really think about it but I feel like there might be non-trivial choices there.

Probably you don't want a "probe" for each expression everytime, so I guess you'll want to resolve which context to use at binding time. I guess we could say: if a global reference exists on `overrideContext` we use it, otherwise we expect it to be found on the normal context as usual. This would:
- require a single test at binding time (or even parsing time if the override context object is already available?)
- support observing undefined properties in the context.

I think the assumption that the `overrideContext` shape is fixed is reasonable. Certainly more so than the context itself.

Drawback is that we might shadow a context property. But people can code around that. Especially if by convention you prefix `overrideContext` properties with say a `$` which is usually understood as a reserved prefix.

Taking this idea to the extreme: decide at parsing time that anything starting with `$` is on `overrideContext`?

**Comment by JoshMcCullough** [comment]
I can't seem to find docs on `with.bind`, do they exist?
