### ISSUE TITLE
Calling Router-View Inside Replaceable Template

### ISSUE THREAD

**Issue by aozisik** [aurelia/templating-resources#179]
I am using childRouters and on this particular page, I try adding my router-view inside of a custom element.

My code is like this:

        <template>
            <require from="components/panel/panel"></require>
            <panel title="Registration">
                <template replace-part="body">
                     <router-view router-view.ref="routerView"></router-view>
                </template>
            </panel>
        </template>

I get the following message (steps/project is the correct child route that should be loaded): 
    
    Error: There was no router-view found in the view for ./steps/project

This might be a weird/rare use case but if it actually worked, it would be very helpful. 

On another note, if I add the router-view as an immediate child to the custom element, I still can't see any results, but it seems to work because it doesn't throw an error message this time.

Is there a work-around to this, a better way of doing it? Or is this something that is missing / will be implemented soon?

**Comment by EisenbergEffect** [comment]
The router-view is not supported in this use case. It must be statically defined within the view for the view-model that defines the router's configuration. Indeed, there was no router-view found in `./steps/project` because you effectively placed it inside the view for the panel. You might want to consider using `<content></content>` instead of a template-part for this use case. Given that you call the part "body" it seems like that would make sense.

For exmaple, your panel view might be like this

```html
<template>
  <div class="panel">
    <content></content>
  </div>
</template>
```

Then content of the `panel` element will be "projected" into the location of the `content` tag inside its view. However, semantically, the content remains inside the panel tag in the view you defined it in.

Template parts literally override a part of an element's view, becoming part of that view at runtime. The content element simply tells content placed inside an element's tag where to render, but does not change the original element's view at all.

**Comment by aozisik** [comment]
Yes, that makes perfect sense. That was really helpful, thank you!

**Comment by EisenbergEffect** [comment]
You are welcome.
