### ISSUE TITLE
Compose doesn't unbind when switching routes between same view, different arguments

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/templating-resources#204]
View A contains a compose tag within
Load view A with argument x 
Switch to View A  (through router.navigate) with argument y

The compose tag doesn't unbind/detach between the calls, and it will reuse the same viewmodel causing undesirable affects.

**Comment by EisenbergEffect** [comment]
I see the explanation, so I could probably reproduce, but I'm wondering if you could drop a quick zip file on this issue that contained the src folder from a repro built on the nav skeleton. That would help us in being sure to resolve this correctly.

**Comment by devteamexpress** [comment]
[src.zip](https://github.com/aurelia/templating-resources/files/177696/src.zip)

**Comment by dilvish4ever** [comment]
Try this. At least it worked for me with one view-model, but different routes (without arguments)
```javascript
import {activationStrategy} from 'aurelia-router';

export class...
...
    determineActivationStrategy() {
        return activationStrategy.invokeLifecycle;
        //OR return activationStrategy.replace;
    }
}
```

**Comment by EisenbergEffect** [comment]
@dilvish4ever is correct. When the params on a route change but it still refers to the same view model, the view does not get re-created; only the new params are passed to the view-model's activate method. This is designed for efficiency. You can change this behavior as noted above. However, you should be able to also databind the attributes of the compose element as well in order to make it recompose regardless of what the router is doing. You may find that binding it's view-model, view or model attributes is a better solution for you.
