### ISSUE TITLE
compose and custom pipeline steps

### ISSUE THREAD

**Issue by ppn2** [aurelia/templating-resources#211]
If custom pipeline steps are added in the router, they are not invoked in the viewModel targeted by compose.

**Comment by jdanyow** [comment]
The compose element is independent of the router- there's no connection between the two.

**Comment by ppn2** [comment]
I have limited understanding of the aurelia internals so correct me if I am wrong. As I understand canActivate, activate, canDeactivate and deactivate hooks are related to router and compose does call these hooks. My understanding is that when we customize the router pipeline, we can create our own hooks and they work similar to activate etc hooks.

My problem is that when I use the component at the top level, my hooks are being called but if I use that component though compose, the hooks are not being called and the component breaks. If you could suggest alternate solution, I would be willing to give it a shot.

**Comment by EisenbergEffect** [comment]
No, compose does not call those hooks. Those hooks are for the router only.
There are two lifecycles, one for navigation and one for components.

Navigation
* canActivate
* activate
* canDeactivate
* deactivate

Components
* created
* bind
* attached
* detached
* unbind

**Comment by ppn2** [comment]
@EisenbergEffect I checked the code and I can see compose is invoking activate and canActivate.

If you look at the [CompositionEngine.createController](https://github.com/aurelia/templating/blob/master/src/composition-engine.js#L125), it is invoking the activate method. The createController method ultimately is being invoked by compose.processInstruction method. 

Though I agree this is hardcoded and not hooked in the router pipeline.

**Comment by EisenbergEffect** [comment]
That's special case code that is mostly only useful for application startup. It's undocumented because it may not be supported in the future and it won't ever be integrated with the router.

**Comment by ppn2** [comment]
So does that mean any component which can be reused should not hook into the activate life cycle? 

We have a requirement where the user can navigate to the url and edit customer screen is presented. Also they can edit the customer in place in a different screen. For example the user is working in the order screen where they can select a customer from the dropdown. We have a edit customer button which pops up a dialog and they can edit the selected customer. In this particular case we are reusing the customer component. Now in the customer component, we need to access the customer data. So we call the web api in the activate method and return a promise. Since activate is called in both the situation (in stand alone page as well as in the dialog, which uses the createController method I mentioned above), everything works fine. But if you say it might not work in the future, we need to rethink our strategy. Do we call the web apis in the bind or attached method? I would welcome your suggestions.

**Comment by EisenbergEffect** [comment]
No, components should use the component lifecycle. Instead of loading data inside of components, create properties and pass the data in.

**Comment by ppn2** [comment]
@EisenbergEffect it seems to me that the activate hook is embedded in quite a many places (e.g. dialog, compose that I can recall from the top of my head) and not supporting it might be quite a breaking a change for lot of people. Besides how would one pass data compose in the absence of activate method, unless new api is introduced or existing api is modified.
With respect to your comment

>  it won't ever be integrated with the router.

this I can understand and appreciate and ok to live with.

**Comment by EisenbergEffect** [comment]
There's no breaking change going on. Nothing has changed in this regard since the initial alpha announcement in February of 1015. There's a lifecycle for components and then there's a lifecycle for navigation. The router and the dialog system both choose to implement the navigation lifecycle. The compose element only supports the activate hook, in order to provide light-weight re-composition of data against the same view/view-model. If you want to create a re-usable component, you should use the component lifecycle. You should avoid loading data inside a component. That is typically the responsibility of the screen's view model which, via bindings, should pass the data to the component for it to render.

So, you should really have two categories of components: "widgets" and "screens". Widgets do should not load data but should receive data through their props. Screens should load data and make it available to bind in their views (including the widgets which reside there).
