### ISSUE TITLE
css bundled (Failed loading required CSS file)

### ISSUE THREAD

**Issue by flieks** [aurelia/templating-resources#220]
Hi,

I get this when i bundle my css (fixUpCSSUrls):
![image](https://cloud.githubusercontent.com/assets/5032389/15092903/8a8a7c50-1477-11e6-887e-a1513b3655b5.png)
the css string is in the "default" property.

maybe it has to do with this
https://github.com/aurelia/templating-resources/issues/189

I'm also getting runtime errors for bundling html:
`Error: Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template> at Object.createTemplateFromMarkup (http://localhost:9000/dist/aurelia.js:10292:15) at eval (http://localhost:9000/dist/aurelia.js:12662:42) Error loading http://localhost:9000/dist/common/contact/index.html!template-registry-entry`

I didn't really changed the gulp bundling code.

**Comment by Ma3yTa** [comment]
I have the same issue

**Comment by Ma3yTa** [comment]
I have the same issue with loading resources registered by config.globalResources [https://gyazo.com/ef5c5cd64d4b3a59f2b3a6910aa35204](https://gyazo.com/ef5c5cd64d4b3a59f2b3a6910aa35204)

**Comment by Ma3yTa** [comment]
When It will be fixed?

**Comment by EisenbergEffect** [comment]
We haven't seen these errors anywhere. We would need a repro to track it down.

**Comment by Ma3yTa** [comment]
https://github.com/Ma3yTa/au-bundle-tst

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Is it possible that the text plugin has changed the way it exports text resources?

**Comment by MisterGoodcat** [comment]
Rob, I also ran into these issues when I followed the simple bundling samples in Aurelia's documentation, and can confirm it's related to the text plugin. Installing 0.0.8 breaks bundling, downgrading to 0.0.3 (as used in the samples) fixes the issue.

**Comment by Ma3yTa** [comment]
@EisenbergEffect @Cedware described where is a problem here https://github.com/aurelia/templating/issues/362#issuecomment-224207102

**Comment by EisenbergEffect** [comment]
Check master of loader-default and let me know if this resolves the issue. Based on examining the source of multiple different loader text plugins and versions, I think this should handle the differing approaches.

**Comment by JayDi85** [comment]
Firefox console show: "TypeError: plugin.load is not a function" when aurelia attempt load css-resources (that's why error "Failed loading required CSS file" raise).

After some research I [found that SO post about that error](http://stackoverflow.com/questions/39399772/unhandled-rejection-error-load-timeout-for-modules-template-registry-entry).

Author found solution in comments to first post:
28 Jul, to dynamically require text requires setting stub:false in the text plugin at aurelia.json > build.loader.plugins.

After change `stub` value to `false` in `aurelia.json` -- work fine for me. Bug is gone and app work correct.
