### ISSUE TITLE
binding focus attribute into a custom element

### ISSUE THREAD

**Issue by qraynaud** [aurelia/templating-resources#230]
I have a simple problem. I have a custom element wrapping an input. I would like dev users to be able to bind focus on it like if it was a normal input:
```html
<my-input focus.bind="hasFocus" label="MyLabel" />
```

I wrote this simple js:
```js
export class MyInputCustomElement {
  @bindable({defaultBindingMode: bindingMode.twoWay}) focus
}
```

And added the relevant code in my element's view:
```html
<input [...] focus.bind="focus" />
```

The binding works fine in my custom element but never gets to the top view using it. I suppose that is because the default `FocusCustomAttribute` interferes. If I replace focus by myFocus in my view and the user binds on my-focus, it works just fine. The issue is that using my-focus instead of focus is counter-intuitive and needs documentation uselessly.

Is there a proper way to do this?

**Comment by EisenbergEffect** [comment]
The issue here is the conflict between the FocusCustomAttribute and your element's property of the same name. To address this, remove the property from your element. Then use an Optional.of(FocusCustomAttribute) to optionally inject the FocusCustomAttribute into your custom element. If it's present, you can observe it's value property. When that changes you can call apis on the input element as appropriate.

**Comment by qraynaud** [comment]
Should have thought about that. It's obvious. Thanks a lot!
