### ISSUE TITLE
click.delegate event does not work within repeat.for

### ISSUE THREAD

**Issue by Awaken6389** [aurelia/templating-resources#25]
Not sure if I'm doing something wrong, but I have an array, I loop through it (with repeat.for) and make a list, each list item has a click.delegate with a function name + id like so:

    <ul>
    <li repeat.for="result of results"> 
        ${result.Percent}% 
        <a click.delegate="SetCategoryID(result.id)">
            <span repeat.for="subcat of result.SubName">${subcat} > </span> ${result.CategoryName}
        </a>
    </li>
    </ul>

Now, if I click on any of the items I get 

	Uncaught Error: SetCategoryID is not a function

If I place a link with the same call anywhere else in the view it goes trough as intended. What am I missing or it's not working as intended?

**Comment by EisenbergEffect** [comment]
You should instead call it like this `$parent.SetCategoryID(result.id)` because the repeater creates a new variable scope. Unfortunately, they don't inherit the variables of the outer block like in JavaScript...yet. We do think we will be able to fix this after some other core improvements are made in our binding engine. In the mean time, you can access those variables with $parent.

**Comment by weoreference** [comment]
Ha this syntax changed yet?

**Comment by nomack84** [comment]
@weoreference not yet...
