### ISSUE TITLE
with.bind array + value converter. Doesn't update

### ISSUE THREAD

**Issue by piwnik** [aurelia/templating-resources#260]
When bind array with 'with.bind' and apply value converter (aka filter), context isn't updated any more (when source array is updated).
So
```html
<ul with.bind="myArray">
    <li repeat.for="item of $this">${item}</li>
 </ul>
```

after 

```javascript
myArray.push('Some value');
```
works as expected and 'Some value' is rendered
but if filter is applied like:
```html
<ul with.bind="myArray | filter">
    <li repeat.for="item of $this">${item}</li>
  </ul>
```

where filter is
```javascript
export class FilterValueConverter {
  toView(array) {
    return array.filter(() => true);
  }
}
```
after 
```javascript
myArray.push('Some value');
```
changes are ignored and new added value isn't displayed (rendered)

Check live example here:
https://gist.run/?id=d26caf1850a81b899ac95d24fdc0900c

**Comment by piwnik** [comment]
As I understand any other attribute (except repeat) doesn't reevaluate array/collection expression after it is changed if value converter is applied. 
Will be this supported in future?

**Comment by EisenbergEffect** [comment]
Ping @jdanyow

**Comment by jdanyow** [comment]
The repeat observes the collection on the right side of the `of` in `repeat.for` binding expression. For example, in `repeat.for="item of foo.bar.baz"`, the repeat will observe the collection returned by the expression `foo.bar.baz`.

In expressions like `repeat.for="item of foo.bar.baz | something"`, the repeat knows that the collection returned by `foo.bar.baz | something` is unlikely to mutate because it's probably a copy of the actual collection returned by the `foo.bar.baz` part of the expression. It has logic to peel apart the expression and access the `foo.bar.baz` part and observe the array there.

When you do something like:
```html
  <ul with.bind="myArray | filter">
    <li repeat.for="item of $this">${item}</li>
  </ul>
```
All the repeat sees is `$this`, it's not able to peel apart the expression and determine that `myArray` is what we really want to observe.

Not a bug, just isn't a supported scenario.
