### ISSUE TITLE
Throttle does not work for two-way bound field

### ISSUE THREAD

**Issue by simonmurdock** [aurelia/templating-resources#268]
**I'm submitting a bug report**

* **Library Version:**
latest

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.1

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
no idea, sorry! see gist 

* **Browser:**
chrome 55.0.2883.95 (64-bit)

* **Language:**
ESnext

**Current behavior:**
When setting a view model property at a high rate, and binding it to a text field, the throttle attribute has no effect. 

**Expected/desired behavior:**
@CasiOo in Gitter was great and helped by setting up this gist which shows the issue:
https://gist.run/?id=0f64bb1e31b62eced006bd88317bad44

You can see that the field is updated in real-time without being throttled.

I also have a screen capture of my app using throttle:
https://gfycat.com/PartialAptEmu
and using debounce:
https://gfycat.com/FirstEminentBullfrog

* **What is the expected behavior?**
That the field only update once a second

* **What is the motivation / use case for changing the behavior?**
In my case it is sharing the page with a 60 FPS canvas which appears to drop to 1 FPS when the value is being updated at a rapid rate. Switching to debounce seems to remove the performance issue, however the field continues to update in real-time without being debounced.

**Comment by jdanyow** [comment]
In a one-way binding (data flows from the model to the view), `throttle` limits the rate at which model updates are applied to the view.

In a two-way binding (data flows in both direction), `throttle` limits the rate at which user data entry updates the model.

In a two-way binding scenario I don't think that throttling model updates to the view makes sense. If model updates are happening so quickly that they need to be throttled, the user would never be able to type something into the input because the input value would immediately be overwritten due to a change in the model. Does this reasoning make sense?

**Comment by simonmurdock** [comment]
That makes sense, you don't want users competing for input against a loop in the view model.

I will have to rethink my UI slightly then. Thank you
