### ISSUE TITLE
Support stylesheet ressources other than CSS

### ISSUE THREAD

**Issue by jods4** [aurelia/templating-resources#272]
Support for CSS resources is hardcoded and what makes it worse is that `_createCSSResource` is not exported either: 
https://github.com/aurelia/templating-resources/blob/0cef07a8cac8e99146d8e1c4b734491bb3dc4724/src/aurelia-templating-resources.js#L61

It would be nice if we added other extensions, or exposed an option or something, so that we could do this:
```html
<require from="styles.less">
```
_I'm not asking that we include a LESS loader!_ But for example in a webpack build, that `style.less` module will contain the resulting CSS code and could be loaded, albeit its extension is not recognized. (i.e. the "less-loader" runs at build time).

**Comment by jods4** [comment]
Note: `.css` is also hardcoded into HMR logic, here: 
https://github.com/aurelia/hot-module-reload/blob/master/src/aurelia-hot-module-reload.ts#L46

So whatever we do to fix this, we should probably also do over there.

**Comment by niieani** [comment]
We have an issue somewhere about making it easier to use other extensions for CSS loading with Aurelia. Perhaps we should just add an attribute on `require` which would tell Aurelia how to treat a certain `require`?

Based on content MIME-types:

```html
<require from="style.less" content="text/css">
```

or with a more "generic" concept of "type":

```html
<require from="style.less" type="css">
```

And then we could internally setup plugins for `content`/`type`s, instead of parsing the filename for that extension, as we do now? It seems like a cleaner way to go about it. The parsing could always serve as a fall back for the default behavior: e.g. when content type is not specified, a module with `.css` name should be always treated as type `text/css`. I'd imagine that when bootstrapping and configuring an Aurelia instance, we could also add hashmaps of "content-type to extensions" which could be used to skip explicit definition of `content` in any of the `<require>` tags.

**Comment by jods4** [comment]
A more generic solution would be nice, but I'm closing this as we now have built-in support for all popular preprocessor.
