### ISSUE TITLE
'show.bind' and 'if.bind' cannot work together with 'repeat.for'.

### ISSUE THREAD

**Issue by boogunote** [aurelia/templating-resources#29]
`$parent` is required to access variable in VM.
Only 
```
 <section show.bind="!$parent.node.collapsed" repeat.for="child of node.children" >
```
can work.
I investigated the reason. `repeat` is a `lifting instruction`.When compiler gets such instruction, the element will be moved under a `template` element. So the execution context of this element is changed.  Only leverage `$parent` can access the variables. You can see it from https://github.com/aurelia/templating/blob/master/src/template-controller.js#L50 

I tried a whole day to fix it, but failed. Seems many parts of code should be changed. So I give up.
I suggest put a warning message at https://github.com/aurelia/templating/blob/master/src/view-compiler.js#L217. It say `'repeat' is a 'lifting instrustion'. Please don't use it with other behaviors.`

**Comment by EisenbergEffect** [comment]
Yes, we will certainly add a warning about that. Apologies for the frustration you experienced. If you think of our `if` and `repeat` the same way as `if` and `for` in JavaScript, it will make sense why these can't be on the same element. They each need to be declared with their own blocks. So, the same is true with our templating engine. We hope to get rid of the need for $parent after some revisions to the binding system, so that should improve. We can add the error message as you suggest as well. Part of the reason we aren't yet RTM is because we do want to put these kinds of meaningful error messages into the system to help people along. Thanks for your patience!

**Comment by EisenbergEffect** [comment]
I think we'll be able to fix this by removing the need for $parent eventually. That should be coming as part of a set of improvements to the binding engine. We are tracking that in another issue. Thanks!
