### ISSUE TITLE
"if" tests are broken

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#307]
Tests use `sut = new If(viewFactory, viewSlot, taskQueue);` and later use `sut.valueChanged(false);` but the `valueChanged` method no longer exists:

https://github.com/aurelia/templating-resources/commit/8b0131aefb8f181fc110e036cae11589bbba1e37#diff-bbce44daacb259a7b129c4fa0d062406

cc @jods4

**Comment by jods4** [comment]
I never got to write new tests for the `else` feature... it's still on my TODO list :(

Moreover when I built `else`, the existing `if` tests failed because of a bug in another Aurelia package, hiding this `valueChanged` failure. I fixed the Aurelia library but didn't notice this :(

Missing tests is one thing that can wait but it's important to fix existing tests so that builds and future PR are green. I'll try to do that ASAP.

**Comment by jods4** [comment]
Uh... seems I can't assign myself in this repo, but I'll try to fix them with a PR anyway ;)

**Comment by jdanyow** [comment]
Thanks @jods4 👍

**Comment by jods4** [comment]
Wow those tests are not great.
The `if` public API has not changed a single bit, yet they all fail now.

Some tests manipulate the internals of `IfCustomAttribute`, in ways that never made sense.

I am removing this test:
```javascript
  it('should do nothing when showing, provided value is falsy and has no view', () => {
    let view = new ViewMock();
    sut.view = null;
    sut.showing = true;
    spyOn(viewSlot, 'remove');
    spyOn(view, 'unbind');

    sut.conditionChanged(false);
    taskQueue.flushMicroTaskQueue();

    expect(viewSlot.remove).not.toHaveBeenCalled();
    expect(view.unbind).not.toHaveBeenCalled();
    expect(sut.showing).toBe(false);
  });
```
Notice that it sets `view = null` and `showing = true` at the beginning (both of those are private implementation details).
I looked at the old code and it is not actually possible that `showing && !view`. So this test is actually describing a behavior that cannot happen.
Because the new code crashes when this impossible internal state happens, this test fails.
I "fixed" it by removing the never-occuring test.
