### ISSUE TITLE
repeat not working as expected

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating-resources#45]
I can't give you a demo right now since I'm waiting on new releases since the repeat binding is currently broken but fixed in #46. This has been working before so some kind of regression must slipped in. I have a sortable plugin that adds a placeholder when you start sorting in a `repeat`binding. The placeholder adds an `element.style.visibility = "hidden"`since it should simulate a real `item` in the `repeat`. However when a sort is finished the `placeholder`is removed and the `items`are sorted. The problem is now that the `item` that you are moving to gets the `placeholder`element (but correct executionContext) since it still has the `element.style.visibility = "hidden"`. So it feels like the wrong view is used in this particular scenario.

Let me know if you need more info and also I will get up a demo asap.

**Comment by martingust** [comment]
@stoffeastrom I've got this reproduced in the demo you linked to in the Gitter channel. Will look into it and get back to you.

**Comment by stoffeastrom** [comment]
@martingust great!

**Comment by martingust** [comment]
@stoffeastrom Instead of pulling views out of the DOM and adding them back again, we are trying to reuse the views as much as possible, this improves the performance a lot. The reason your sortable plugin worked before was due to the lack of view reuse in the repeat that got introduced in the v0.10.0 release of templating resource. 

In certain scenarios like yours and 3:rd party jQuery plugins that mutate the DOM we would like to have way to opt out of view reuse, I have created an issue for this here: https://github.com/aurelia/templating-resources/issues/49. Also we are planing on implementing a cache mechanism for views, that would most likely solve this kind of problems without the need of disabling view reuse in the repeat.

However when looking at your sortable plugin I'm wonder if there is a way for you to achieve what you are doing without mutating the DOM? Would it be possible to data bind to the `image.media.placeholder` property and based on that set a css class that hides the element?

Like:

`<div class="col-sm-6 col-md-3 ${image.media.placeholder ? 'placeholder' : '' }" repeat.for="image of images" sortable-item="item.bind: image;">`

**Comment by stoffeastrom** [comment]
@martingust That is ofc possible. However, doing that the plugin relies on that the user sets the correct css. It would be nice if that just works ootb. Maybe it will be possible to have plugin scoped css in the long run which would be awesome.

**Comment by martingust** [comment]
@stoffeastrom I see, hmmm. Would it be possible to implement the `detached` or `unbind` callback and reset the styling?

**Comment by EisenbergEffect** [comment]
Definitely, if your plugin alters html, then I would make sure to appropriately destroy the plugin during the `detached` or `unbind` callback.

**Comment by stoffeastrom** [comment]
@martingust  @EisenbergEffect. I will try that. As long as the unbind is called for the placeholder element before setting the new executioncontext it wouldn't be a problem.

**Comment by stoffeastrom** [comment]
`detached` is not called since the view isn't destroyed which makes sense. The unbind is called but not for the element that I'm removing..

**Comment by stoffeastrom** [comment]
Sry, I forgot to use latest build.. it actually calls `detached`.

**Comment by stoffeastrom** [comment]
So I implemented the `detached`callback and it works as expected!

**Comment by EisenbergEffect** [comment]
Awesome!

**Comment by martingust** [comment]
Great, looking forward to see the demos of your plugin.

**Comment by stoffeastrom** [comment]
Sorry guys but after some more testing I found out that it doesn't work 100%. When moving a element left to right it works however moving from right to left it doesn't. Neither `detached` nor `unbind` is called for the `placeholder` element

**Comment by martingust** [comment]
Ok, sorry won't be able to check it out tonight. Let me know if you find out anything or i'll take a look.

**Comment by stoffeastrom** [comment]
@martingust @EisenbergEffect 
I would argue that this is a bug after some more investigation. I get different `view lifecycles` and it doesn't seem consistent. It's kind of hard to get a minimal example but in pseudo

After a `repeat` is rendered add an `item`
I expect the following `view` functions to be called
`bind`, `attached`
When moving the newly added `item` I expect nothing
When removing the newly added `item` I expect
`unbind`, `detached`
to be called.

Trying out different scenarios for above. Meaning moving the item forward or backwards in the array yields in different `view lifecycle` events and they are not always triggered for the correct `view`.

Best thing would be if we could get some scenarios up and running in unit tests but I'm not sure how that should be done.

**Comment by martingust** [comment]
@stoffeastrom You are absolutely right. Since the view gets reused detached and attached never get fired. This would get solved when the view caching is in place, which should be within the next couple of weeks. Hope this doesn't cause too much trouble for you or you can do temporary workaround maybe with CSS.

**Comment by martingust** [comment]
Actually I'll reopen this, so we can track when caching is in place.

**Comment by stoffeastrom** [comment]
@martingust @EisenbergEffect 

Even if a `view` is reused shouldn't we make sure to follow the `view lifecycle`?
In my opinion we should still follow the `view lifecycle` but with the correct `execution context`.

What I'm saying is that I still want `view` caching for performance but ensure the `view lifecycle`.

In my case, if `bind` and `unbind` would be called with correct `execution context` it would just work.

Thoughts?

**Comment by stoffeastrom** [comment]
Thinking more of it we could even call `attached` and `detached` meaning that the `view` is `attached`, `detached`. If there are use cases you would want to know if it's `attached`/`detached` to the DOM we could add those events

**Comment by EisenbergEffect** [comment]
Yes, absolutely. We have a "quickie" version in the repeater. But, we are going to remove that and implement caching at the view factory and view slot level. This will ensure enable the full lifecycle to be preserved even while re-using views. The repeater then will have it's custom logic removed. That's the plan at least.

**Comment by stoffeastrom** [comment]
Great!
