### ISSUE TITLE
Shadow DOM with dynamically created components

### ISSUE THREAD

**Issue by cehoffman** [aurelia/templating-resources#52]
Currently to my understanding components which dynamically insert other components, e.g. router-view and compose, do not obey the `@useShadowDOM` decorator of the component they insert. This is unintuitive and breaks the declarative assumptions decorators afford.

Is it intended that code which uses `@useShadowDOM` and wants to mess with its own DOM should have something like the following to proactively allow use with these dynamic components?

```js
import {inject, useShadowDOM} from 'aurelia-framework';

@useShadowDOM
@inject(Element)
export class MyShadowDOM {
  constructor(el) {
    this.shadowRoot = el.shadowRoot || el;
  }
}
```

Granted I haven't played with the polyfill in browsers that don't have a shadow dom implementation so the above may be best practice just to satisfy them. That use case however really needs other thinking to ensure any CSS used is sufficiently isolated then.

**Comment by EisenbergEffect** [comment]
Once a shadow root is created on something like the `compose` or `router-view` it can't be removed. So...suppose you navigated to one screen that wanted shadow dom and another that didn't. You couldn't support both scenarios. Ordering of events would cause non-shadow-dom screens to fail after one that required it was rendered.

That issue aside, I'm not sure that using shadow DOM for "screens" is a good idea. It's a good fit for widgets, but not screens. The reason is that there's no way to share css, use css frameworks or anything like that from within shadow dom.

**Comment by cehoffman** [comment]
After using this in practice much more I agree that creating shadow DOM for these dynamic view ports creates more harm than good.
