### ISSUE TITLE
show and class on the same element

### ISSUE THREAD

**Issue by manuel-guilbault** [aurelia/templating-resources#62]
The ```show``` attached behavior conflicts with the ```class``` HTML attribute with string interpolation when used on the same element.

For example, given the following template:
```
<div show.bind="isVisible" class="${isEnabled ? '' : 'disabled'}"></div>
``` 

When ```isVisible``` is set to false, and ```show``` adds ```aurelia-hide``` to the element's ```classList```,
and then ```isEnabled``` is set to true, then the ```class``` attribute is overwritten, and the element loses the ```aurelia-hide``` class, and the element becomes visible.

**Comment by manuel-guilbault** [comment]
Maybe this could be solved by adding an attached behavior that uses the new dynamicOptions to toggle on and off a set of classes. Something like:
```
<div show.bind="isVisible" classes="disabled.bind: !isEnabled; another-class.bind: isSomethingElse()"></div>
```

**Comment by EisenbergEffect** [comment]
@jdanyow We need to look into this issue shortly. We've got another feature that is going to cause this bug to crop up more frequently in the future. The new ability I'm working on next week to enable custom element host properties to be bound to internal properties of the view model could result in multiple class bindings on the same element: one provided by the element itself and bound to the element's view model and another provided by the consumer of the element and bound to the surrounding view's data context.

We need to think about how we can extend our class binding in the binding engine to track what classes it has added, so that it doesn't mess with other classes. As a result, we probably need to special case how string interpolation works with classes.

Let me know if you get a chance to look into what it would take to fix this.

**Comment by jdanyow** [comment]
ok will take a look

**Comment by jdanyow** [comment]
related to https://github.com/aurelia/binding/issues/33

**Comment by EisenbergEffect** [comment]
Also related to this (once I implement the new feature): https://github.com/aurelia/templating/issues/61

**Comment by jdanyow** [comment]
@EisenbergEffect if you get a chance could you review this commit:  https://github.com/jdanyow/binding/commit/f579a8de6cde891aeecc4db9793f19724b03c3fa

I added a new observer type:  `ClassObserver`.  It tracks the classes it's added so that it doesn't remove someone else's classes.  The big thing is `ClassObserver` is never shared.  The ObserverLocator will always return a new instance.

Working on the tests now.

My integration test looked like this:
```html
<template>
  <div show.bind="show" class.bind="class" class="${foo ? 'foo' : ''} ${bar ? 'bar' : ''} ${baz ? 'baz' : ''}">
    hello world
  </div>
</template>
```
```javascript
export class App {
  constructor() {
    this.randomize();
    setInterval(() => this.randomize(), 2000);
  }

  randomize() {
    var r = Math.floor(Math.random() * 3);
    this.foo = r === 0;
    this.bar = r === 1;
    this.baz = r === 2;
    this.class = ['one', 'two', 'three'][r] + ' test'
    this.show = Math.floor(Math.random() * 5) !== 0;
  }
}
```

**Comment by EisenbergEffect** [comment]
Looks pretty good. I had one comment, but it's not a big deal. Let me know when you are done with the tests and we'll get it in. This will fix several issues and enable the new host element binding feature. Thanks!
