### ISSUE TITLE
Custom element if.bind and repeat.for race condition causes repeat.for duplicates

### ISSUE THREAD

**Issue by decademoon** [aurelia/templating-resources#84]
This is kind of hard to explain, but is simple to reproduce here: http://plnkr.co/edit/dcNDjqmzm72bwT4yikDl

Basically I'm getting duplicate rows with `repeat.for` in this very specific situation: If there's a `repeat.for` inside a custom element, and the custom element's visibility is controlled with an `if.bind`, and these two events occur at the same time:

1. The array bound to the `repeat.for` is set to a new array instance.
2. The element is hidden as a result of the `if.bind`.

Then the old items that the `repeat.for` created aren't removed from the DOM, even though binding to the `repeat.for` was set to a new instance.

If the second event above is performed in the next tick (with a timeout of 0), then it works correctly.

**Comment by jdanyow** [comment]
@decademoon, thanks for the plunkr and the troubleshooting details.  As a workaround could you use `show.bind` instead of `if.bind`?

@EisenbergEffect I'm wondering if this would be fixed if we made the `if` behavior's `valueChanged` work lowest priority by enqueuing it on the micro-task-queue?  If that sounds like a reasonable approach I could investigate whether using the task queue would indeed fix this issue.

**Comment by EisenbergEffect** [comment]
@jdanyow My concern with doing that is that it might push view construction out late enough to cause additional DOM churn during the initial UI render. For exmaple if the main view is then added to the DOM before the if binding renders its child view, then you will have a second forced layout/render from the DOM which wasn't there before...and this could happen a lot depending on the number of if bindings you had. So, if you were going to push it onto the microtask queue, I would need you to verify that it wasn't causing the above problem.

Are we sure this isn't a bug in the repeater implementation? @martingust might be able to help in looking into that as well.

**Comment by martingust** [comment]
@jdanyow @EisenbergEffect It looks like the problem is that repeater does not remove its views when the events occur at the same time. 

`if` triggers the call to the repeater's `unbind` method before the task queue gets flushed which results in that the repeater does not remove any views. 

When the event is triggered on the next tick the task queue gets flushed and the repeater removes the views and then `unbind` is called.

In other words `unbind` gets called which sets `disposeSubscription` to null (https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L90) and then when the task queue gets flushed and the repeater process the items the views does not get removed (https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L103)

I'm not too familiar with the task queue but is this something we can control from outside of the repeater or should the repeater handle this scenario?

**Comment by EisenbergEffect** [comment]
@martingust I think this is likely something we will have to handle at the repeater level. Would having the if delay calling unbind via a micro task help the issue?

**Comment by martingust** [comment]
@EisenbergEffect That might help. I will investigate further.

**Comment by martingust** [comment]
@EisenbergEffect Awesome, delay the unbind call with the micro task did fix the issue. I'll put together a PR today or tomorrow.

**Comment by dredzone** [comment]
same problem still exists in beta when compose is used to construct the view.
```
<compose if.bind="active" view-model="./${viewModel}"></compose>
```
