### ISSUE TITLE
How to dynamically render a custom element

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/templating-resources#91]
I can use `compose` to dynamically render a `model/view/view-model`. 

But how do I dynamically render a **custom element** from its type? Given a `ViewModel` where I know the `Type` of child custom element that I want to add to my `View`, I'd need something like this:

    <template>
       <${customElementType} param1.bind="p1" param2.bind="p2"/>
    </template>

**Comment by ZapMyR** [comment]
I'm not sure if I understand your problem correctly, but I'd still use a `compose` in the `template` and bind its `view-model` property to a string from your viewmodel to dynamically render the desired custom element and design the choosable custom elements to take in an array of params instead of multiple parameters that are individually bound.

**Comment by jdanyow** [comment]
This is not possible because the view-compiler determines what custom elements, custom attributes and bindings are in the template once, at "view compilation time", not at "bind time".  Continue to use compose for dynamic scenarios like this.
