### ISSUE TITLE
two-way binding not working as expected with jQuery plugin

### ISSUE THREAD

**Issue by corydeppen** [aurelia/templating-resources#92]
I've added a Kendo ComboBox to a form using a [global-behavior](http://aurelia.io/docs.html#global-behavior) and two-way binding. It renders as expected and changes to the select are reflected in the model, but changes in the model are not reflected in the select.

```
<div value.two-way="app.WorkspaceLevelId"
     jquery.kendocombobox="dataSource.bind: dataSource; dataTextField.bind: 'Name'; dataValueField.bind: 'WorkspaceLevelId'"></div>
```

If I were to change `value.two-way` to `value.bind` it appears as though it's treated as one-time binding, as the value is only set when the widget is instantiated but the select never changes the model from that point forward.

Should two-way binding work in these behaviors?

**Comment by EisenbergEffect** [comment]
Unfortunately, the global behavior doesn't know how to automatically enable two-way behavior on arbitrary jquery plugins. That usually involves knowing how the events of the plugin report changes so that data can be pushed back in the opposite direction.

The global behavior is a bit of an experimental feature, since we're not sure how helpful it will really be. Perhaps you can investigate whether or not there's a way we can add some additional, simple configuration to the behavior that would enable it to do two-way binding? If there's a significantly generic solution that's possible, we would be happy to take a pull request.
